jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      nexus:
        image: sonatype/nexus3
        ports:
          - 8081:8081
          - 8082:8082

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: ./mvnw clean test -Dtest="!PostgresIntegrationTests"

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rowida2_Spring-Petclinic-Project -Dtest="!PostgresIntegrationTests"

      - name: Build Docker image
        run: docker build -t petclinic-app:${{ github.sha }} .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: petclinic-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Wait for Nexus to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8081/service/rest/v1/status > /dev/null; then
              echo "Nexus is up"
              break
            fi
            echo "Waiting for Nexus..."
            sleep 10
          done

      - name: Get Nexus admin password
        run: |
          NEXUS_CONTAINER=$(docker ps -qf "ancestor=sonatype/nexus3")
          NEXUS_PASS=$(docker exec "$NEXUS_CONTAINER" cat /nexus-data/admin.password)
          echo "::add-mask::$NEXUS_PASS"
          echo "NEXUS_PASS=$NEXUS_PASS" >> "$GITHUB_ENV"

      - name: Create Docker hosted repository in Nexus
        run: |
          curl -u admin:"$NEXUS_PASS" -X POST "http://localhost:8081/service/rest/v1/repositories/docker/hosted" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "docker-hosted",
              "online": true,
              "storage": {"blobStoreName": "default", "strictContentTypeValidation": true, "writePolicy": "allow"},
              "docker": {"v1Enabled": false, "forceBasicAuth": true, "httpPort": 8082}
            }'

      - name: Push image to Nexus
        run: |
          echo "$NEXUS_PASS" | docker login localhost:8082 -u admin --password-stdin
          docker tag petclinic-app:${{ github.sha }} localhost:8082/petclinic-app:${{ github.sha }}
          docker push localhost:8082/petclinic-app:${{ github.sha }}